sudo: required

services:
  - docker

language: python

install:
  - pip install yq

script:
  # Ensure we can build ARM images
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # Build images
  - docker-compose build
  - docker-compose -f docker-compose-collectd.yml build
  # Does it run?
  - |
    IMAGE=$(docker-compose config | yq -r .services.gateway.image)
    echo "Gateway image is: ${IMAGE}"
    docker run --rm "${IMAGE}" /opt/ttn-gateway/mp_pkt_fwd
  # Push images to the docker hub for the master branch
  - |
    if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]
    then
      docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
      IMAGE=$(docker-compose config | yq -r .services.gateway.image)
      TAG=$(docker run --rm "${IMAGE}" /opt/ttn-gateway/mp_pkt_fwd | awk '/Version:/ && NF==2 {print $NF}')
      IMAGES_PROMETHEUS=$(docker-compose config | yq -r '.services | .[].image')
      IMAGES_COLLECTD=$(docker-compose -f docker-compose-collectd.yml config | yq -r '.services | .[].image')
      for IMAGE in ${IMAGES_PROMETHEUS} ${IMAGES_COLLECTD}
      do
      echo "Pushing ${IMAGE} to the docker hub; Tag: ${TAG}"
        docker tag "${IMAGE}" "${IMAGE}:${TAG}"
        docker push "${IMAGE}:${TAG}"
        docker push "${IMAGE}"
      done
    fi
