# Docker-compose file for TTN gateway

# Version 2.1 for resin compatibility
version: '2.1'
services:
  # The gateway itself
  gateway:
    build: gateway
    image: ttn/pi-gateway
    privileged: true
    restart: always
    environment:
      GW_EUI: "${GW_EUI}"
      GW_KEY: "${GW_KEY}"
      GW_ID: "${GW_ID}"
      GW_LOGGER: "true"
    devices:
      - "/dev/mem:/dev/mem"
    volumes:
      - var_ttn_vol:/var/ttn

volumes:
  var_ttn_vol:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
