# Docker-compose file for TTN gateway
# Prometheus reporting stack
# Requires docker-compose 1.9 or newer

# Version 2.1 for resin compatibility
version: '2.1'
services:
  # The gateway itself
  gateway:
    build: gateway
    image: amedee/ttn-gateway
    privileged: true
    network_mode: host
    restart: always
    environment:
      GW_KEY: "${GW_KEY:?Gateway Key is mandatory}"
      GW_ID: "${GW_ID:?Gateway Id is mandatory}"
      GW_EUI: "${GW_EUI}"
      GW_LOGGER: "${GW_LOGGER:-false}"
    devices:
      - "/dev/mem:/dev/mem"
    volumes:
      - var_ttn_vol:/var/ttn
  # Prometheus exporter
  prom-exporter:
    build: prom-exporter
    image: amedee/ttn-prom-exporter
    privileged: true
    restart: always
    # "link" is not supported in resin, we bind to localhost
    ports:
      - "127.0.0.1:9100:9100"
  # TTN exporter
  exporter:
    build: exporter
    image: amedee/ttn-exporter
    privileged: true
    # Exporter ned to access localhost to call prom-exporter
    network_mode: host
    restart: always
    volumes:
      - var_ttn_vol:/var/ttn

volumes:
  var_ttn_vol:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
